"""empty message

Revision ID: 5a1be5a004c3
Revises: 7f15ff9a9197
Create Date: 2022-08-31 22:17:32.808136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1be5a004c3'
down_revision = '7f15ff9a9197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('messages', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###
