"""empty message

Revision ID: 7f15ff9a9197
Revises: 3c9f49e8e251
Create Date: 2022-08-31 21:52:19.783046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f15ff9a9197'
down_revision = '3c9f49e8e251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
